# Generated by Django 3.0.4 on 2020-04-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('started', models.DateTimeField(null=True)),
                ('finished', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('success', 'SUCCESS'), ('failure', 'FAILURE'), ('continue', 'CONTINUE'), ('not_started', 'NOT STARTED')], default='not_started', max_length=11)),
                ('step', models.PositiveIntegerField()),
                ('data_filepath', models.FileField(upload_to='uploaded_tasks/')),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task_list',
            },
        ),
    ]
